#!/usr/bin/env python3
"""Complete exact audit of the one authorized split holomorph P semidirect B.

P=H_3(3) x C3^2 has coordinates (x,y,u,v,z), with carry x*y' in z.
B=Hom(F3^2,F3^3) semidirect <T> is the canonical full-translation
completion generated by alpha,beta,gamma.  Every one of the 3^12 elements is
cubed.  This script does not search any alternate action or factor system.
"""

from collections import Counter
from hashlib import sha256


def cadd(a, b):
    return ((a[0]+b[0])%3, (a[1]+b[1])%3, (a[2]+b[2])%3)


def cscale(a, s):
    return ((s*a[0])%3, (s*a[1])%3, (s*a[2])%3)


def tpow(k, c):
    # T: u->u+v, v->v+z, z->z, in coordinate order (u,v,z).
    k %= 3
    if k == 0:
        return c
    if k == 1:
        return (c[0], (c[1]+c[0])%3, (c[2]+c[1])%3)
    return (c[0], (c[1]+2*c[0])%3, (c[2]+2*c[1]+c[0])%3)


def pmul(p, q):
    return ((p[0]+q[0])%3, (p[1]+q[1])%3,
            (p[2]+q[2])%3, (p[3]+q[3])%3,
            (p[4]+q[4]+p[0]*q[1])%3)


def fcols(f):
    return f[:3], f[3:]


def fadd(f, g):
    return tuple((a+b)%3 for a,b in zip(f,g))


def tf(k, f):
    a,b = fcols(f)
    return tpow(k,a) + tpow(k,b)


def feval(f, x, y):
    a,b = fcols(f)
    return cadd(cscale(a,x), cscale(b,y))


def bact(f, k, p):
    shifted = cadd(tpow(k, p[2:]), feval(f,p[0],p[1]))
    return (p[0],p[1]) + shifted


def bmul(b, d):
    f,k = b
    g,l = d
    return (fadd(f,tf(k,g)), (k+l)%3)


def hmul(h, j):
    p,b = h
    q,d = j
    return (pmul(p,bact(b[0],b[1],q)), bmul(b,d))


Z6 = (0,)*6
P0 = (0,)*5
B0 = (Z6,0)
ONE = (P0,B0)


def hcube(h):
    h2 = hmul(h,h)
    return hmul(h2,h)


P = tuple((x,y,u,v,z) for x in range(3) for y in range(3)
          for u in range(3) for v in range(3) for z in range(3))
FS = tuple((a,b,c,d,e,f) for a in range(3) for b in range(3)
           for c in range(3) for d in range(3) for e in range(3) for f in range(3))
B = tuple((f,k) for f in FS for k in range(3))

cubes = set()
for b in B:
    for p in P:
        cubes.add(hcube((p,b)))

cube_list = sorted(cubes)
cube_digest = sha256(repr(cube_list).encode("ascii")).hexdigest()
cube_projection = {b for _,b in cubes}
base_fibres = Counter(b for _,b in cubes)

cube_cubes_identity = all(hcube(g) == ONE for g in cubes)
has_nontrivial_cube = any(g != ONE for g in cubes)

embedded_P = {(p,B0) for p in P}

closure_defect = None
for g in cube_list:
    for h in cube_list:
        gh = hmul(g,h)
        if gh not in cubes:
            closure_defect = (g,h,gh)
            break
    if closure_defect is not None:
        break

noncommuting = None
for i,g in enumerate(cube_list):
    for h in cube_list[i+1:]:
        if hmul(g,h) != hmul(h,g):
            noncommuting = (g,h,hmul(g,h),hmul(h,g))
            break
    if noncommuting is not None:
        break

print("P_order", len(P))
print("B_order", len(B))
print("H_order", len(P)*len(B))
print("enumerated_all_H_elements", len(P)*len(B))
print("cube_of_every_cube_is_identity", cube_cubes_identity)
print("exponent_exactly_9", cube_cubes_identity and has_nontrivial_cube)
print("literal_cube_count", len(cubes))
print("literal_cube_sha256", cube_digest)
print("cube_projection_to_B_count", len(cube_projection))
print("cube_projection_fibre_distribution", dict(sorted(Counter(base_fibres.values()).items())))
print("literal_cubes_equal_embedded_P", cubes == embedded_P)
print("literal_cube_set_closed", closure_defect is None)
print("closure_defect", closure_defect)
print("noncommuting_cube_pair", noncommuting)

