H := SmallGroup(252,2);
M := SmallGroup(252,1);
A := AutomorphismGroup(M);
homs := AllHomomorphismClasses(H,A);
f := homs[1];
Print("IMAGE_ORDER=",Size(Image(f)),"\n");
ext := SemidirectProduct(H,f,M);
Print("E_ORDER=",Size(ext)," E_IS_PC=",IsPcGroup(ext),"\n");
Print("EMBEDDING_1_SOURCE_SIZE=",Size(Source(Embedding(ext,1))),"\n");
Print("EMBEDDING_2_SOURCE_SIZE=",Size(Source(Embedding(ext,2))),"\n");
n1 := Image(Embedding(ext,1));;
n2 := Image(Embedding(ext,2));;
Print("EMBEDDING_1_NORMAL=",IsNormal(ext,n1)," EMBEDDING_2_NORMAL=",IsNormal(ext,n2),"\n");
msub := n2;
t := Runtime();;
comps := ComplementClassesRepresentatives(ext,msub);
Print("COMPLEMENT_CLASSES=",Length(comps)," RUNTIME_MS=",Runtime()-t,"\n");
QUIT;
