#!/usr/bin/env python3
"""Independent q=7 incidence and resolution checker, version 2.

Projective points/lines are generated by disjoint affine charts.  Resolutions
are counted by memoized dynamic programming on a 21-bit covered-point mask.
"""

from functools import cache

F = 7
NONSQUARES = {3, 5, 6}


def chart():
    return ([(1, y, z) for y in range(F) for z in range(F)]
            + [(0, 1, z) for z in range(F)] + [(0, 0, 1)])


def norm(v):
    v = tuple(a % F for a in v)
    k = next(k for k, a in enumerate(v) if a)
    r = pow(v[k], -1, F)
    return tuple(r * a % F for a in v)


def quadratic(v):
    x, y, z = v
    return (y * y - x * z) % F


def incidence(point, line):
    return sum(a * b for a, b in zip(point, line)) % F == 0


def determinant(rows):
    (a, b, c), (d, e, f), (g, h, i) = rows
    return (a*(e*i-f*h) - b*(d*i-f*g) + c*(d*h-e*g)) % F


points = tuple(chart())
lines = points
conic = frozenset(v for v in points if quadratic(v) == 0)
internal = tuple(sorted(v for v in points if quadratic(v) in NONSQUARES))
number = {v: k for k, v in enumerate(internal)}
full_mask = (1 << len(internal)) - 1
assert (len(points), len(conic), len(internal)) == (57, 8, 21)


def bitmask(vectors):
    answer = 0
    for v in vectors:
        answer |= 1 << number[norm(v)]
    return answer


secant_lines = tuple(
    line for line in lines
    if sum(incidence(c, line) for c in conic) == 2
)
geometric = frozenset(
    bitmask(v for v in internal if incidence(v, line))
    for line in secant_lines
)
assert len(secant_lines) == len(geometric) == 28
assert all(block.bit_count() == 3 for block in geometric)

raw = ((1,0,1), (3,1,1), (5,2,1), (2,0,1), (4,0,1), (6,4,1))
assert tuple(quadratic(v) for v in raw) == (6,5,6,5,3,3)
P, A, B, C, D, R = tuple(norm(v) for v in raw)
assert all(quadratic(v) in NONSQUARES for v in (P,A,B,C,D,R))

old_triples = ((P,A,B), (P,C,D), (A,C,R), (B,D,R))
new_triples = ((P,A,C), (P,B,D), (A,B,R), (C,D,R))
old = frozenset(bitmask(block) for block in old_triples)
new = frozenset(bitmask(block) for block in new_triples)
assert old <= geometric
assert not (new & geometric)
assert all(determinant(block) != 0 for block in new_triples)
traded = (geometric - old) | new
assert len(traded) == 28


def gram(blocks):
    entries = []
    for i in range(21):
        for j in range(i, 21):
            pair = (1 << i) | (1 << j)
            if i == j:
                entries.append(sum(bool(block & (1 << i)) for block in blocks))
            else:
                entries.append(sum((block & pair) == pair for block in blocks))
    return tuple(entries)


assert gram(geometric) == gram(traded)


def resolution_count(blocks):
    blocks = tuple(sorted(blocks))
    through = tuple(tuple(b for b in blocks if b & (1 << i)) for i in range(21))

    @cache
    def count(covered):
        if covered == full_mask:
            return 1
        uncovered = full_mask ^ covered
        pivot_bit = uncovered & -uncovered
        pivot = pivot_bit.bit_length() - 1
        return sum(count(covered | b) for b in through[pivot] if not (covered & b))

    return count(0)


print(f"points={len(points)} conic={len(conic)} internal={len(internal)}")
print(f"geometric_blocks={len(geometric)} traded_blocks={len(traded)}")
print(f"raw_q_values={tuple(quadratic(v) for v in raw)}")
print(f"new_determinants={tuple(determinant(b) for b in new_triples)}")
print(f"gram_equal={gram(geometric) == gram(traded)}")
print(f"geometric_resolutions={resolution_count(geometric)}")
print(f"traded_resolutions={resolution_count(traded)}")
