# Independent Validator audit for the p=3 order-3^8 reduction.
#
# This implementation does two exact checks over every official group of order
# 3^7.  First, for every exponent-9 row it forms the complete actual cube set
# and tests whether the subgroup generated by those values is abelian.  Second,
# for the class-5/6 rows it tests subgroup closure directly by products and
# inverses, then cross-checks that result against the size of the generated
# subgroup.  It does not enumerate central extensions or descendants.

orderTarget := 3^7;;
expectedGroups := 9310;;

loadedSmallGrp := LoadPackage("smallgrp");;
Print("VALIDATOR_ORDER2187_BEGIN gap_version=", GAPInfo.Version,
      " smallgrp_loaded=", loadedSmallGrp, "\n");

if loadedSmallGrp <> true then
  Print("STATUS=BLOCKER reason=smallgrp_load_failed\n");
else
  if not SmallGroupsAvailable(orderTarget) then
    Print("STATUS=BLOCKER reason=order_2187_data_unavailable\n");
  else
    numberGroups := NumberSmallGroups(orderTarget);;
    Print("library_order=", orderTarget,
          " group_count=", numberGroups, "\n");

    if numberGroups <> expectedGroups then
      Print("STATUS=BLOCKER reason=unexpected_group_count expected=",
            expectedGroups, " observed=", numberGroups, "\n");
    else
      countVisited := 0;;
      countExponent9 := 0;;
      countNoncommutingCubeValues := 0;;
      countClass56 := 0;;
      countClass56Nontrivial := 0;;
      countClass56Subgroup := 0;;
      countClosureCrosscheckMismatch := 0;;
      baseHits := [];;

      for id in [1..numberGroups] do
        groupRow := SmallGroup(orderTarget, id);;
        countVisited := countVisited + 1;;

        if Exponent(groupRow) = 9 then
          countExponent9 := countExponent9 + 1;;
          actualCubes := Set(Elements(groupRow), g -> g^3);;
          generatedByCubes := Subgroup(groupRow, actualCubes);;

          if not IsAbelian(generatedByCubes) then
            countNoncommutingCubeValues :=
              countNoncommutingCubeValues + 1;;
            Print("NONCOMMUTING_CUBE_ROW id=", id,
                  " cube_values=", Length(actualCubes), "\n");
          fi;

          nilClass := NilpotencyClassOfGroup(groupRow);;
          if nilClass = 5 or nilClass = 6 then
            countClass56 := countClass56 + 1;;

            if Length(actualCubes) > 1 then
              countClass56Nontrivial := countClass56Nontrivial + 1;;
            fi;

            hasIdentity := One(groupRow) in actualCubes;;
            inverseClosed := ForAll(actualCubes,
                                    a -> a^-1 in actualCubes);;
            productClosed := ForAll(actualCubes,
                                    a -> ForAll(actualCubes,
                                                b -> a*b in actualCubes));;
            directSubgroupTest := hasIdentity and inverseClosed
                                  and productClosed;;
            generatedSizeTest :=
              Size(generatedByCubes) = Length(actualCubes);;

            if directSubgroupTest <> generatedSizeTest then
              countClosureCrosscheckMismatch :=
                countClosureCrosscheckMismatch + 1;;
              Print("CLOSURE_CROSSCHECK_MISMATCH id=", id, "\n");
            fi;

            Print("CLASS56_ROW id=", id,
                  " class=", nilClass,
                  " cube_values=", Length(actualCubes),
                  " generated_size=", Size(generatedByCubes),
                  " identity=", hasIdentity,
                  " inverse_closed=", inverseClosed,
                  " product_closed=", productClosed,
                  " subgroup=", directSubgroupTest, "\n");

            if directSubgroupTest then
              countClass56Subgroup := countClass56Subgroup + 1;;
              Add(baseHits, id);
            fi;
          fi;
        fi;

        if id mod 1000 = 0 then
          Print("PROGRESS id=", id,
                " exp9=", countExponent9,
                " noncommuting_cube_rows=",
                countNoncommutingCubeValues,
                " class56=", countClass56,
                " class56_subgroup=", countClass56Subgroup, "\n");
        fi;
      od;

      Print("VALIDATOR_COMPLETE=yes visited=", countVisited,
            " exp9=", countExponent9,
            " noncommuting_cube_rows=", countNoncommutingCubeValues,
            " class56=", countClass56,
            " class56_nontrivial=", countClass56Nontrivial,
            " class56_subgroup=", countClass56Subgroup,
            " closure_crosscheck_mismatch=",
            countClosureCrosscheckMismatch, "\n");
      Print("BASE_HITS=", baseHits, "\n");
      Print("STATUS=VALIDATOR_ORDER2187_DEPENDENCIES_COMPLETE\n");
    fi;
  fi;
fi;
