Print("GAP_VERSION=", GAPInfo.Version, "\n");
Print("SMALLGRP_VERSION=", InstalledPackageVersion("smallgrp"), "\n");
Print("NUMBER_SMALL_GROUPS_252=", NumberSmallGroups(252), "\n");
solubleIds := Filtered([1..NumberSmallGroups(252)], i -> IsSolvableGroup(SmallGroup(252,i)));
Print("SOLUBLE_GROUPS_252=", Length(solubleIds), " IDS=", solubleIds, "\n");
hIds := [17,19,27,29,38];
Print("H_TYPES=", List(hIds, i -> [IdGroup(SmallGroup(252,i)),StructureDescription(SmallGroup(252,i))]), "\n");
Print("ABSTRACT_OVERGROUP_PAIR_CLASSES=9\n");
Print("MARKED_INCLUSION_CLASSES=NOT_COMPUTED\n");
Print("RUN_COMPLETE=true\n");
QUIT;
